[package]
name = "arbre"
version = "0.1.0"
authors = ["luke-bhan <luke.bhan@vanderbilt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
rand = "0.7.3"
deflate = "0.8.6"
hex = "0.4.2"
